services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=apppass123
      - POSTGRES_USER=appuser
      - POSTGRES_DB=appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - 5432:5432

  mongo:
    image: mongo:7
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    ports:
      - 27017:27017

  redis:
    image: redis:7
    container_name: redis_db
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - 6379:6379
  
  ms-identity:
    depends_on:
      - postgres
      - redis
    build: 
      context: ./ms-identity
      dockerfile: Dockerfile
    container_name: ms_identity
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - POSTGRES_CONNECTION=Host=postgres;Port=5432;Database=appdb;Username=appuser;Password=apppass123
      - REDIS_CONNECTION=redis:6379
    networks:
      - app_network
    ports:
      - 5001:8080
    
  domain_1:
    depends_on:
      - postgres
      - redis
    build:
      context: ./domain_1
      dockerfile: Dockerfile
    container_name: domain_1
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - MONGO_CONNECTION=mongodb://mongo:27017
      - REDIS_CONNECTION=redis:6379
    networks:
      - app_network
    ports:
      - 5002:8080

  domain_2:
    depends_on:
      - postgres
      - redis
    build:
      context: ./domain_2
      dockerfile: Dockerfile
    container_name: domain_2
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - POSTGRES_CONNECTION=Host=postgres;Port=5432;Database=appdb;Username=appuser;Password=apppass123
    networks:
      - app_network
    ports:
      - 5003:8080
    
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data: